# Generated by Django 3.0.8 on 2020-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
