# Generated by Django 3.0.8 on 2020-07-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20200728_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='size',
        ),
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
