# Generated by Django 3.0.8 on 2020-07-31 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_ratinng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinng',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
