# Generated by Django 3.0.8 on 2020-08-02 01:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0006_auto_20200731_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratinng',
            new_name='Rating',
        ),
    ]
