# Generated by Django 3.0.8 on 2020-08-03 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0006_auto_20200731_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratinng',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.Category'),
        ),
    ]
